image: quarkus-native-image.yaml
imageName: quay.io/quarkus/ubi-quarkus-native-image
buildScript: .github/build-native-images.sh
versions:
  - 20.2.0-java11
  - 20.3.0-java11
  - 20.3.1-java11
  - 21.0.0-java11
tags:
  - id: 20.2-java11
    target: 20.2.0-java11
  - id: 20.3-java11
    target: 20.3.0-java11    
  - id: 21.0-java11
    target: 21.0.0-java11    
versionCheck: true
