image: quarkus-native-s2i.yaml
imageName: quay.io/quarkus/ubi-quarkus-native-s2i
buildScript: .github/build-s2i-native-images.sh
versions:
  - 21.3.2-java11
  - 21.3.2-java17
  - 22.0.0-java11
  - 22.0.0-java17
  - 22.1.0-java11
  - 22.1.0-java17
tags:  
  - id: 21.3-java11
    target: 21.3.2-java11
  - id: 21.3-java17
    target: 21.3.2-java17
  - id: 22.0-java11
    target: 22.0.0-java11
  - id: 22.0-java17
    target: 22.0.0-java17    
  - id: 22.1-java11
    target: 22.1.0-java11
  - id: 22.1-java17
    target: 22.1.0-java17        
versionCheck: false
