image: quarkus-tooling.yaml
imageName: quay.io/quarkus/centos-quarkus-maven
buildScript: .github/build-tooling-images.sh
versions:
  - 21.3.2-java11
  - 22.0.0-java11-amd64
  - 22.1.0-java11-amd64
tags:
  - id: 21.3-java11
    target: 21.3.2-java11
  - id: 22.0-java11-amd64
    target: 22.0.0-java11-amd64
  - id: 22.1-java11-amd64
    target: 22.1.0-java11-amd64
versionCheck: false
