#!/bin/sh

# This POC script is based on the openshift/source-to-image project documentation,
# and loosely inspired by fabric8io-images/s2i's assemble script, but **MUCH** simplified;
# a TODO future PRODUCTION version of this would probably want to re-use that script...

set -ex

#############################################
# Configure maven - for a complete list of
# supported values, please refer the module.yaml
# file.
CONFIGURE_SCRIPTS=(
  ${APP_HOME}/.m2/configure-maven.sh
)
source ${APP_HOME}/.m2/configure.sh
#############################################

SRC_DIR=${SRC_DIR:-'/tmp/src/'}

cd $SRC_DIR

if [ -e ./pom.xml -a -z "$USE_GRADLE" ]; then
    USE_GRADLE=false
else
    USE_GRADLE=true
fi

 if "$USE_GRADLE"; then
  BUILD_DIR=build
  mkdir -p build/libs
  gradle build -Dquarkus.package.type=native
else
  if [ -z "$ARTIFACT_DIR" ]; then
    BUILD_DIR=target
  else
    BUILD_DIR=$ARTIFACT_DIR
  fi
  mvn package -Pnative -e -B \
    -DskipTests -Dmaven.javadoc.skip=true -Dmaven.site.skip=true -Dmaven.source.skip=true \
    -Djacoco.skip=true -Dcheckstyle.skip=true -Dfindbugs.skip=true -Dpmd.skip=true \
    -Dfabric8.skip=true ${MVN_ADDITIONAL_ARGS}

fi

cp -v ${BUILD_DIR}/*-runner ${APP_HOME}/application
chmod +x ${APP_HOME}
chmod +x ${APP_HOME}/application